### PR TITLE
Update/7.1

### PR DESCRIPTION
**Pull request by Alluneve**
Welcome to 7.1.
ClientStructs had shit hit the fan, so I had to be patient.

Did version updates, verified functionality, and applied necessary changes.

edit: verified functionality means I went through all the scenarios in REGRESSIONTESTS.MD and they all pass

### CODE REVIEW

**Comment by icesharkk** [comment]
mod author seems MIA. is there a way for me to get this branch working?

**Comment by Alluneve** [comment]
The author is not missing in action, just be patient.

Baylee will get to this pull request someday, probably within a week or 2.

Officially a plugin is only considered abandoned if not updated for 4-6 months after a dalamud Api bumb, as per dalamud adoption policy.

The level of impatience expressed by the people using this or xiv combo is frankly not that nice, we're not paid to do maintain this and it's our free time.

**Comment by icesharkk** [comment]
impatience yes, but im not upset or anything. i dont expect them to have completed all this free work already. hence why i posted here seeing if there was a way to for me move onto the branch you have. was not trying to throw shade at the author.

**Comment by Alluneve** [comment]
if you need to ask how to get code from a GitHub to local, then build it yourself to run a dev plugin in Dalamud for testing something before it's generally available in a testing release you can just get through the plugin manager, then you're probably not the audience for even attempting to do so.

before general availability, the only people who I don't mind "getting it early" are those who are at least technical enough to analyze logs properly and can already halfway pinpoint the source of an issue if an issue arrives that's not: "it doesn't work". and then at least open an issue or notify me of the problem.

so please just be patient, general availability will be there soon ™

**Comment by Alluneve** [comment]
Stuff done today was some house cleaning and changing some ToString() calls into ExtractText() calls on items of type ReadyOnlySeString. because it's less heavy to turn a readOnlySePayoadSpan into text that way than to do it with the StringBuilder....

had to force-push because I didn't have my full source at lunch and needed to verify what I did this evening

**Comment by attickdoor** [comment]
ty fam

**Comment by Alluneve** [comment]
always a pleasure

**Pull request merged**
